# Generated by Django 4.0.3 on 2022-05-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='costo',
            field=models.FloatField(default=0),
        ),
    ]
