# Generated by Django 4.0.3 on 2022-05-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cotizaciones', '0002_cliente_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='costo',
            field=models.CharField(max_length=200),
        ),
    ]
