# Generated by Django 4.0.3 on 2022-05-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pensionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('edad_actual', models.IntegerField(default=0)),
                ('edad_retiro', models.IntegerField(default=0)),
                ('saldo_acumulado', models.FloatField(default=9.99)),
                ('ahorro_mensual', models.FloatField(default=9.99)),
                ('genero', models.IntegerField(blank=True, choices=[(1, 'Hombre'), (2, 'Mujer')], null=True)),
            ],
        ),
    ]
