package cliente;

import cliente.Cliente;
import estres.Globals;

import javax.swing.*;
import java.awt.*;

public class GameFrame extends javax.swing.JFrame {

    private javax.swing.JButton[] botones;
    private String name;
    private Cliente cliente;
    private int currTopo = -1;

    public GameFrame() {
        initComponents();
    }

    private void registro() {

        ImageIcon img = new ImageIcon(getClass().getClassLoader().getResource("imagenes/nasa.jpg"));
        ImageIcon iconoCohete = new ImageIcon(img.getImage().getScaledInstance(145, -1, java.awt.Image.SCALE_SMOOTH));
        img = new ImageIcon(getClass().getClassLoader().getResource("imagenes/doge.png"));
        ImageIcon iconodoge = new ImageIcon(img.getImage().getScaledInstance(145, -1, java.awt.Image.SCALE_SMOOTH));
        while (this.name == null || this.name.equals("")) {
            this.name = (String) JOptionPane.showInputDialog(rootPane,
                    "Name:", "Get the Doge!",
                    JOptionPane.INFORMATION_MESSAGE, iconoCohete, null, "");
            if (this.name == null || this.name.equals("")) {
                if (JOptionPane.showConfirmDialog(null,"Empty name! \n \n Exit game?",
                        "Get the Doge!", JOptionPane.YES_NO_OPTION,
                        0, iconodoge) == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        }
        this.cliente = new Cliente(this, name);
    }

    private void comenzar() {
        registro();
        cliente.start();
        while (!cliente.isInGame()) {
            JOptionPane.showMessageDialog(this, "Name already used! \n \n Please, write another name.");
            this.name = "";
            registro();
            cliente.start();
        }
        this.botones = new javax.swing.JButton[] {
                doge1, doge2, doge3, doge4, doge5, doge6, doge7, doge8, doge9, doge10
        };
        usuario.setText(this.name);
        puntaje.setText("0");

    }

    private void clicOnButton(int id) {
        puntaje.setText(Integer.toString(golpeaTopo(id)));
    }

    public void reportWinner(String winner) {
        ImageIcon img = new ImageIcon(getClass().getClassLoader().getResource("imagenes/doge.png"));
        ImageIcon icono = new ImageIcon(img.getImage().getScaledInstance(145, -1, java.awt.Image.SCALE_SMOOTH));
        if (name.equals(winner)) {
            if (JOptionPane.showConfirmDialog(null, "Congratulations! You're the winner! \n \n Do you want to play again?", "Finished Game",
                    JOptionPane.YES_NO_OPTION, 0, icono) == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        } else {
            if (JOptionPane.showConfirmDialog(null, "Game over! \n \n Do you want to play again?", "Finished Game!",
                    JOptionPane.YES_NO_OPTION, 0, icono) == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        }
        changeTopo(-1);
        puntaje.setText("0");
    }

    public void changeTopo(int id) {
        if (currTopo != -1) {
            botones[currTopo].setIcon(null);
        }
        currTopo = id;
        if (id != -1)
            botones[currTopo].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/doge_topo.png")));
    }

    public int golpeaTopo(int i) {
        if (!cliente.isInGame()) {
            JOptionPane.showMessageDialog(this, "Enter a game first!");
            return -1;
        }
        return cliente.hitTopo(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        puntaje = new javax.swing.JLabel();
        doge1 = new javax.swing.JButton();
        doge2 = new javax.swing.JButton();
        doge3 = new javax.swing.JButton();
        doge4 = new javax.swing.JButton();
        doge5 = new javax.swing.JButton();
        doge6 = new javax.swing.JButton();
        doge7 = new javax.swing.JButton();
        doge8 = new javax.swing.JButton();
        doge9 = new javax.swing.JButton();
        doge10 = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Get the Doge!");

        contenedor.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Points:");
        jLabel1.setForeground(Color.WHITE);
        contenedor.add(jLabel1);
        jLabel1.setBounds(430, 0, 110, 30);

        usuario.setText("<usuario>");
        usuario.setForeground(Color.WHITE);
        contenedor.add(usuario);
        usuario.setBounds(180, 0, 180, 30);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Player:");
        jLabel2.setForeground(Color.WHITE);
        contenedor.add(jLabel2);
        jLabel2.setBounds(70, 0, 110, 30);

        puntaje.setText("<puntaje>");
        puntaje.setForeground(Color.WHITE);
        contenedor.add(puntaje);
        puntaje.setBounds(540, 0, 80, 30);

        doge1.setBorderPainted(false);
        doge1.setContentAreaFilled(false);
        doge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doge1ActionPerformed(evt);
            }
        });
        contenedor.add(doge1);
        doge1.setBounds(30, 40, 70, 60);

        doge2.setBorderPainted(false);
        doge2.setContentAreaFilled(false);
        doge2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doge2ActionPerformed(evt);
            }
        });
        contenedor.add(doge2);
        doge2.setBounds(270, 30, 70, 60);

        doge3.setBorderPainted(false);
        doge3.setContentAreaFilled(false);
        doge3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doge3ActionPerformed(evt);
            }
        });
        contenedor.add(doge3);
        doge3.setBounds(620, 200, 70, 60);

        doge4.setBorderPainted(false);
        doge4.setContentAreaFilled(false);
        doge4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doge4ActionPerformed(evt);
            }
        });
        contenedor.add(doge4);
        doge4.setBounds(70, 250, 70, 60);

        doge5.setBorderPainted(false);
        doge5.setContentAreaFilled(false);
        doge5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doge5ActionPerformed(evt);
            }
        });
        contenedor.add(doge5);
        doge5.setBounds(250, 200, 70, 60);

        doge6.setBorderPainted(false);
        doge6.setContentAreaFilled(false);
        doge6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doge6ActionPerformed(evt);
            }
        });
        contenedor.add(doge6);
        doge6.setBounds(70, 400, 70, 60);

        doge7.setBorderPainted(false);
        doge7.setContentAreaFilled(false);
        doge7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doge7ActionPerformed(evt);
            }
        });
        contenedor.add(doge7);
        doge7.setBounds(420, 320, 70, 60);

        doge8.setBorderPainted(false);
        doge8.setContentAreaFilled(false);
        doge8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doge8ActionPerformed(evt);
            }
        });
        contenedor.add(doge8);
        doge8.setBounds(570, 340, 70, 60);

        doge9.setBorderPainted(false);
        doge9.setContentAreaFilled(false);
        doge9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doge9ActionPerformed(evt);
            }
        });
        contenedor.add(doge9);
        doge9.setBounds(500, 80, 70, 60);

        doge10.setBorderPainted(false);
        doge10.setContentAreaFilled(false);
        doge10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doge10ActionPerformed(evt);
            }
        });
        contenedor.add(doge10);
        doge10.setBounds(290, 380, 70, 60);

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/space.png"))); // NOI18N
        contenedor.add(imagen);
        imagen.setBounds(0, 0, 730, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doge1ActionPerformed
        clicOnButton(0);
    }//GEN-LAST:event_doge1ActionPerformed

    private void doge2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doge2ActionPerformed
        clicOnButton(1);
    }//GEN-LAST:event_doge2ActionPerformed

    private void doge3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doge3ActionPerformed
        clicOnButton(2);
    }//GEN-LAST:event_doge3ActionPerformed

    private void doge4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doge4ActionPerformed
        clicOnButton(3);
    }//GEN-LAST:event_doge4ActionPerformed

    private void doge5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doge5ActionPerformed
        clicOnButton(4);
    }//GEN-LAST:event_doge5ActionPerformed

    private void doge6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doge6ActionPerformed
        clicOnButton(5);
    }//GEN-LAST:event_doge6ActionPerformed

    private void doge7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doge7ActionPerformed
        clicOnButton(6);
    }//GEN-LAST:event_doge7ActionPerformed

    private void doge8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doge8ActionPerformed
        clicOnButton(7);
    }//GEN-LAST:event_doge8ActionPerformed

    private void doge9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doge9ActionPerformed
        clicOnButton(8);
    }//GEN-LAST:event_doge9ActionPerformed

    private void doge10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doge10ActionPerformed
        clicOnButton(9);
    }//GEN-LAST:event_doge10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Globals.debugMode = false;
                GameFrame guacamole = new GameFrame();
                guacamole.comenzar();
                guacamole.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel puntaje;
    private javax.swing.JLabel usuario;
    private javax.swing.JButton doge1;
    private javax.swing.JButton doge10;
    private javax.swing.JButton doge2;
    private javax.swing.JButton doge3;
    private javax.swing.JButton doge4;
    private javax.swing.JButton doge5;
    private javax.swing.JButton doge6;
    private javax.swing.JButton doge7;
    private javax.swing.JButton doge8;
    private javax.swing.JButton doge9;
    // End of variables declaration//GEN-END:variables


}
