/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import cliente.Cliente;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author padillandrea
 */
public class GameFrame extends javax.swing.JFrame {
    private javax.swing.JButton[] botones;
    private String name;
    private Cliente cliente;
    private int currTopo = -1;

    /**
     * Creates new form Guacamole
     */
    public GameFrame() {
        initComponents();
    }
    
    private void registro() {
        ImageIcon img = new ImageIcon(getClass().getClassLoader().getResource("imagenes/jabon.png"));
        ImageIcon iconoJabon = new ImageIcon(img.getImage().getScaledInstance(145, -1, java.awt.Image.SCALE_SMOOTH));
        img = new ImageIcon(getClass().getClassLoader().getResource("imagenes/virus.png"));
        ImageIcon iconoVirus = new ImageIcon(img.getImage().getScaledInstance(145, -1, java.awt.Image.SCALE_SMOOTH));
        while (this.name == null || this.name.equals("")) {
            this.name = (String) JOptionPane.showInputDialog(rootPane,
                    "Escribe tu nombre:", "¡Pégale al virus! Registro del jugador",
                    JOptionPane.INFORMATION_MESSAGE, iconoJabon, null, "");
            if (this.name == null || this.name.equals("")) {
                if (JOptionPane.showConfirmDialog(null,"Tu nombre está vacío. \n \n ¿Deseas salir del juego?",
                        "¡Pégale al virus!", JOptionPane.YES_NO_OPTION,
                        0, iconoVirus) == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        }
        this.cliente = new Cliente(this, name);
    }
    
    private void comenzar() {
        registro();
        cliente.start();
        while (!cliente.inGame) {
            JOptionPane.showMessageDialog(this, "Ya hay un jugador con ese nombre. \n \n Por favor registra otro nombre.");
            this.name = "";
            registro();
            cliente.start();
        }
        this.botones = new javax.swing.JButton[] {
            virus1, virus2, virus3, virus4, virus5, virus6, virus7, virus8, virus9, virus10
        };
        usuario.setText(this.name);
        puntaje.setText("0");
        
    }
    
    private void clicOnButton(int id) {
        puntaje.setText(Integer.toString(golpeaTopo(id)));
    }
    
    public void reportWinner(String winner) {
        ImageIcon img = new ImageIcon(getClass().getClassLoader().getResource("imagenes/virus.png"));
        ImageIcon icono = new ImageIcon(img.getImage().getScaledInstance(145, -1, java.awt.Image.SCALE_SMOOTH));
        if (name.equals(winner)) {
            if (JOptionPane.showConfirmDialog(null, "Felicidades, ganaste. \n \n ¿Quieres unirte a la siguiente partida?", "¡El juego ha terminado!",
                JOptionPane.YES_NO_OPTION, 0, icono) == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        } else {
            if (JOptionPane.showConfirmDialog(null, "Ya hay un ganador. \n \n ¿Quieres unirte a la siguiente partida?", "¡El juego ha terminado!",
                JOptionPane.YES_NO_OPTION, 0, icono) == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        }
        cambiaTopo(-1);
        puntaje.setText("0");
    }
    
    public void cambiaTopo(int id) {
        if (currTopo != -1) {
            botones[currTopo].setIcon(null);
        }
        currTopo = id;
        if (id != -1)
            botones[currTopo].setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/topo.png")));
        
    }
    
    public int golpeaTopo(int i) {
        if (!cliente.inGame) {
            JOptionPane.showMessageDialog(this, "Entra a una partida primero");
            return -1;
        }
        return cliente.golpeaTopo(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        puntaje = new javax.swing.JLabel();
        virus1 = new javax.swing.JButton();
        virus2 = new javax.swing.JButton();
        virus3 = new javax.swing.JButton();
        virus4 = new javax.swing.JButton();
        virus5 = new javax.swing.JButton();
        virus6 = new javax.swing.JButton();
        virus7 = new javax.swing.JButton();
        virus8 = new javax.swing.JButton();
        virus9 = new javax.swing.JButton();
        virus10 = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("¡Pégale al virus!");

        contenedor.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Puntuación:");
        contenedor.add(jLabel1);
        jLabel1.setBounds(430, 0, 110, 30);

        usuario.setText("<usuario>");
        contenedor.add(usuario);
        usuario.setBounds(180, 0, 180, 30);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jugador (a):");
        contenedor.add(jLabel2);
        jLabel2.setBounds(70, 0, 110, 30);

        puntaje.setText("<puntaje>");
        contenedor.add(puntaje);
        puntaje.setBounds(540, 0, 80, 30);

        virus1.setBorderPainted(false);
        virus1.setContentAreaFilled(false);
        virus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virus1ActionPerformed(evt);
            }
        });
        contenedor.add(virus1);
        virus1.setBounds(30, 40, 70, 60);

        virus2.setBorderPainted(false);
        virus2.setContentAreaFilled(false);
        virus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virus2ActionPerformed(evt);
            }
        });
        contenedor.add(virus2);
        virus2.setBounds(270, 30, 70, 60);

        virus3.setBorderPainted(false);
        virus3.setContentAreaFilled(false);
        virus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virus3ActionPerformed(evt);
            }
        });
        contenedor.add(virus3);
        virus3.setBounds(620, 200, 70, 60);

        virus4.setBorderPainted(false);
        virus4.setContentAreaFilled(false);
        virus4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virus4ActionPerformed(evt);
            }
        });
        contenedor.add(virus4);
        virus4.setBounds(70, 250, 70, 60);

        virus5.setBorderPainted(false);
        virus5.setContentAreaFilled(false);
        virus5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virus5ActionPerformed(evt);
            }
        });
        contenedor.add(virus5);
        virus5.setBounds(250, 200, 70, 60);

        virus6.setBorderPainted(false);
        virus6.setContentAreaFilled(false);
        virus6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virus6ActionPerformed(evt);
            }
        });
        contenedor.add(virus6);
        virus6.setBounds(70, 400, 70, 60);

        virus7.setBorderPainted(false);
        virus7.setContentAreaFilled(false);
        virus7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virus7ActionPerformed(evt);
            }
        });
        contenedor.add(virus7);
        virus7.setBounds(420, 320, 70, 60);

        virus8.setBorderPainted(false);
        virus8.setContentAreaFilled(false);
        virus8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virus8ActionPerformed(evt);
            }
        });
        contenedor.add(virus8);
        virus8.setBounds(570, 340, 70, 60);

        virus9.setBorderPainted(false);
        virus9.setContentAreaFilled(false);
        virus9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virus9ActionPerformed(evt);
            }
        });
        contenedor.add(virus9);
        virus9.setBounds(500, 80, 70, 60);

        virus10.setBorderPainted(false);
        virus10.setContentAreaFilled(false);
        virus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virus10ActionPerformed(evt);
            }
        });
        contenedor.add(virus10);
        virus10.setBounds(290, 380, 70, 60);

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubrebocas.jpg"))); // NOI18N
        contenedor.add(imagen);
        imagen.setBounds(0, 0, 730, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void virus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virus1ActionPerformed
        clicOnButton(0);
    }//GEN-LAST:event_virus1ActionPerformed

    private void virus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virus2ActionPerformed
        clicOnButton(1);
    }//GEN-LAST:event_virus2ActionPerformed

    private void virus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virus3ActionPerformed
        clicOnButton(2);
    }//GEN-LAST:event_virus3ActionPerformed

    private void virus4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virus4ActionPerformed
        clicOnButton(3);
    }//GEN-LAST:event_virus4ActionPerformed

    private void virus5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virus5ActionPerformed
        clicOnButton(4);
    }//GEN-LAST:event_virus5ActionPerformed

    private void virus6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virus6ActionPerformed
        clicOnButton(5);
    }//GEN-LAST:event_virus6ActionPerformed

    private void virus7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virus7ActionPerformed
        clicOnButton(6);
    }//GEN-LAST:event_virus7ActionPerformed

    private void virus8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virus8ActionPerformed
        clicOnButton(7);
    }//GEN-LAST:event_virus8ActionPerformed

    private void virus9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virus9ActionPerformed
        clicOnButton(8);
    }//GEN-LAST:event_virus9ActionPerformed

    private void virus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virus10ActionPerformed
        clicOnButton(9);
    }//GEN-LAST:event_virus10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameFrame guacamole = new GameFrame();
                guacamole.comenzar();
                guacamole.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel puntaje;
    private javax.swing.JLabel usuario;
    private javax.swing.JButton virus1;
    private javax.swing.JButton virus10;
    private javax.swing.JButton virus2;
    private javax.swing.JButton virus3;
    private javax.swing.JButton virus4;
    private javax.swing.JButton virus5;
    private javax.swing.JButton virus6;
    private javax.swing.JButton virus7;
    private javax.swing.JButton virus8;
    private javax.swing.JButton virus9;
    // End of variables declaration//GEN-END:variables
}
